spring:
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://13.114.99.144/amsdb?serverTimezone=JST&allowMultiQueries=true
      username: ams
      password: ams!23456
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
          pool-name: ConnectionPool
          leakDetectionThreshold: 5000
          connection-test-query: SELECT 1
          minimum-idle: 5
          maximum-pool-size: 10
          auto-commit: false

mybatis:
   configuration:
      map-underscore-to-camel-case: true
      default-fetch-size: 100
      default-statement-timeout: 30
   type-aliases-package: jp.co.info.ais.ams.domain
   mapper-locations: classpath*:/mapper/**/*.xml

server:
   port: 8080

constant:
   companyCode: AIS
   
   # spring boot의 기본 properties
server.error:
  include-exception: false
  include-stacktrace: never # 오류 응답에 stacktrace 내용을 포함할 지 여부
  path: '/error' # 오류 응답을 처리할 Handler의 경로
  whitelabel.enabled: true # 서버 오류 발생시 브라우저에 보여줄 기본 페이지 생성 여부