spring:
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/supplies?serverTimezone=JST
      username: admin
      password: admin

mybatis:
   configuration:
      map-underscore-to-camel-case: true
      default-fetch-size: 100
      default-statement-timeout: 30
   type-aliases-package: com.example.demo.domain
   mapper-locations: classpath*:/mapper/**/*.xml

server:
   port: 8081